# Sowa Engine scene file
name = "scene"
version = 1
active_camera_2d = 120

[[filesystem]]

[[filesystem]]
path = "res://kenney.png"
flags = 0b11

[[filesystem]]
path = "res://music.ogg"
flags = 0b11

[nodes]

[nodes.12]
name = "Root"
type = "Node"
parent = 0

# [nodes.121]
# name = "Test Panel"
# type = "NineSlicePanel"
# parent = 12
# texture.path = "res://uv.jpg"
# size.x = 700.0
# size.y = 500.0
# margin.left = 64.0
# margin.right = 64.0
# margin.top = 64.0
# margin.bottom = 64.0

[nodes.122]
name = "Child Node"
type = "Node2D"
parent = 12
position.x = 10.0
position.y = 10.0
rotation = 0.0
scale.x = 1.0
scale.y = 1.0

[nodes.120]
name = "Main Camera"
type = "Camera2D"
parent = 12
position.x = 200.0
position.y = 200.0
rotation = 100.0
zoom.x = 1.0
zoom.y = 1.0
rotatable = true

[nodes.123]
name = "Sprite"
type = "Sprite2D"
parent = 12
position.x = 700.0
position.y = 200.0
scale.x = 0.5
scale.y = 0.5
texture.path = "res://kenney.png"

[nodes.124]
name = "A Text"
type = "Text2D"
position.x = -200
position.y = -200
parent = 12
text = "This is not very long text"

[nodes.125]
name = "My Player"
type = "AudioStreamPlayer"
parent = 12
stream.path = "res://laserShoot.wav"


[nodes.126]
name = "Music player"
type = "AudioStreamPlayer"
parent = 12
stream.path = "res://music.ogg"
autostart = false